const data = {
  products: [
    {
      name: 'Nike Slim Shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Adidas Fit Shirts',
      slug: 'adidas-fit-shirts',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 180,
      countInStock: 15,
      brand: 'adidas',
      rating: 4.2,
      numReviews: 12,
      description: 'good quality shirt',
    },
    {
      name: 'nike Slim pants',
      slug: 'nike-slim-pants',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 350,
      countInStock: 6,
      brand: 'nike',
      rating: 4.6,
      numReviews: 20,
      description: 'excellent quality pants',
    },
    {
      name: 'adidas Slim pants',
      slug: 'adidas-slim-pants',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 250,
      countInStock: 12,
      brand: 'adidas',
      rating: 4.1,
      numReviews: 15,
      description: 'normal quality pants',
    },
  ],
};

export default data;
